# Site settings for Tran Thanh Luan's personal website
locale                   : "en-US"
site_theme               : "default"
title                    : "Tran Thanh Luan - AI Engineer & Researcher"
title_separator          : "-"
name                     : &name "Tran Thanh Luan"
description              : &description "AI Engineer specializing in generative AI, MLOps, and decentralized systems"
url                      : https://yourusername.github.io # Update with your GitHub username
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "yourusername/yourusername.github.io" # Update with your GitHub username

# Site Author
author:
  # Biographic information
  avatar           : "profile.png" # Add a profile image to your repository
  name             : "Tran Thanh Luan"
  pronouns         : # example: "he/him"  
  bio              : "AI Engineer & Researcher with expertise in generative AI, MLOps, and decentralized systems"
  location         : "Hanoi, Vietnam"
  employer         : "Condenses.AI"
  uri              : # URL
  email            : "tranthanhluan.nd@gmail.com" 

  # Academic websites
  arxiv            : # URL
  googlescholar    : # URL
  impactstory      : # URL
  orcid            : # URL
  semantic         : # URL
  pubmed           : # URL
  researchgate     : # URL
  scopus           : # URL

  # Repositories and software development
  bitbucket        : # Username
  codepen          : # Username
  dribbble         : # Username
  github           : # Replace with your GitHub username
  kaggle           : # Username  
  stackoverflow    : # User number

  # Social media
  bluesky          : # Username
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : # Your LinkedIn username
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : # Username for X / Twitter
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # Username

# Publication Category
publication_category:
  research:
    title: 'Research Papers'
  projects:
    title: 'AI Projects'

# Site Settings
teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "enabled" # "enabled" or "disabled" (default)
talkmap_link             : false
comments:
  provider               : false # false (default)

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-analytics-4", "custom"

# These settings control the types of collections used by the template
collections:
  experience:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  research:
    output: true
    permalink: /:collection/:path/

# These settings control how pages and collections are included in the site
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _experience
  - scope:
      path: ""
      type: experience
    values:
      layout: single
      author_profile: true
      share: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true
  # _research
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Ho_Chi_Minh # Timezone for Vietnam

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
